
"""
Data augmentation module for MolCraft.
Handles random charge, distortion, and size augmentation.
"""

import sys
import random
import logging
from pathlib import Path
from typing import List, Tuple,  Optional

import numpy as np
import torch
from tqdm import tqdm

from ase.db import connect
from ase.symbols import symbols2numbers
from mendeleev import element

# Try importing PyG dependencies (similar to random_charge.py)
try:
    from torch_geometric.utils import to_networkx
    import networkx as nx
except ImportError:
    pass

logger = logging.getLogger(__name__)

CUTOFF = 3
SCALE_FACTOR = 1.2
CSV_FIELDS = ['filename', 'total_charge', 'num_atoms', 'num_graph']

# --- Chemistry Helpers ---

def get_electronegativity(element_symbol):
    try:
        return element(element_symbol).en_pauling
    except Exception:
        logger.error(f"Could not retrieve electronegativity for {element_symbol}")
        raise

def read_xyz(filename) -> Tuple[List[str], np.ndarray]:
    with open(filename, 'r') as f:
        lines = f.readlines()
    atom_count = int(lines[0])
    atoms = []
    coords = []
    for line in lines[2:2 + atom_count]:
        parts = line.split()
        atoms.append(parts[0])
        coords.append([float(x) for x in parts[1:4]])
    return atoms, np.array(coords)

def write_xyz(filename, atoms, coords):
    with open(filename, 'w') as f:
        f.write(f"{len(atoms)}\nGenerated by augmentation\n")
        for atom, coord in zip(atoms, coords):
            f.write(f"{atom} {coord[0]:.6f} {coord[1]:.6f} {coord[2]:.6f}\n")

# --- Augmentation Logic: Random Charge ---

def add_h_unit(atoms: List[str], coords: np.ndarray) -> Optional[Tuple[List[str], np.ndarray, int]]:
    """Adds a single hydrogen to a non-halogen heteroatom."""
    halogens = ['F', 'Cl', 'Br', 'I']
    heteroatom_indices = [i for i, atom in enumerate(atoms) 
                          if atom not in ['C', 'H'] and atom not in halogens]

    if not heteroatom_indices:
        return None

    # Pick random heteroatom
    idx = random.choice(heteroatom_indices)
    coord = coords[idx]
    elem = atoms[idx]

    # Find non-clashing position
    new_h_coord = None
    for _ in range(50):
        vec = np.random.randn(3)
        vec /= np.linalg.norm(vec)
        proposed = coord + vec * 1.0 # 1.0 Angstrom distance
        
        # Simple clash check
        dists = np.linalg.norm(coords - proposed, axis=1)
        if np.min(dists) >= 0.8:
            new_h_coord = proposed
            break
            
    if new_h_coord is None:
        return None

    new_atoms = list(atoms) + ['H']
    new_coords = np.vstack([coords, new_h_coord])
    
    # Charge logic: If heteroatom is more EN than H, adding H increases charge?
    # Original logic: limit charge increment
    charge_inc = 1 if get_electronegativity(elem) > get_electronegativity('H') else -1
    return new_atoms, new_coords, charge_inc

def remove_h_unit(atoms: List[str], coords: np.ndarray) -> Optional[Tuple[List[str], np.ndarray, int]]:
    """Removes a single hydrogen."""
    h_indices = [i for i, atom in enumerate(atoms) if atom == 'H']
    if not h_indices: return None
    
    idx = random.choice(h_indices)
    h_coord = coords[idx]
    
    # Find bonded atom
    dists = np.linalg.norm(coords - h_coord, axis=1)
    dists[idx] = float('inf') # Ignore self
    bonded_idx = np.argmin(dists)
    
    elem = atoms[bonded_idx]
    charge_inc = -1 if get_electronegativity(elem) > get_electronegativity('H') else 1
    
    new_atoms = [atom for i, atom in enumerate(atoms) if i != idx]
    new_coords = np.delete(coords, idx, axis=0)
    
    return new_atoms, new_coords, charge_inc

def augment_charge(
    input_source: str, # xyz_dir or db_path
    output_target: str, # output_dir or output_db
    max_h_change: int = 1,
    fraction: float = 1.0,
    seed: int = None,
    is_db_mode: bool = False,
):
    """
    Main function for random charge augmentation via H addition/removal + XTB re-optimization.
    """
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)

    if is_db_mode:
        # DB Implementation
        pass
    else:
        # XYZ Implementation
        input_dir = Path(input_source)
        output_dir = Path(output_target)
        output_dir.mkdir(exist_ok=True, parents=True)
        
        xyz_files = sorted(list(input_dir.glob("*.xyz")))
        if fraction < 1.0:
            xyz_files = random.sample(xyz_files, int(len(xyz_files) * fraction))
            
        for xyz_file in tqdm(xyz_files, desc="Augmenting Charge"):
            atoms, coords = read_xyz(xyz_file)
            
            # Decide action based on H counts
            n_change = random.randint(1, max_h_change)
            actions = []
            if len([a for a in atoms if a == 'H']) >= n_change: actions.append('remove')
            if any(a not in ['C', 'H'] for a in atoms): actions.append('add')
            
            if not actions: continue
            action = random.choice(actions)
            
            curr_atoms, curr_coords = list(atoms), coords.copy()
            total_charge = 0
            
            valid = True
            for _ in range(n_change):
                res = None
                if action == 'add': res = add_h_unit(curr_atoms, curr_coords)
                elif action == 'remove': res = remove_h_unit(curr_atoms, curr_coords)
                
                if res:
                    curr_atoms, curr_coords, inc = res
                    total_charge += inc
                else:
                    valid = False
                    break
            
            if not valid: continue
            
            # XTB Optimization Step
            # ... (Requires subprocess call to xtb)
            # Placeholder for actual XTB call integration
            logger.info(f"Augmented {xyz_file.name}: {action} {n_change} H, Charge {total_charge}")


# --- Augmentation Logic: Distortion ---

def create_pyg_graph(cartesian_coordinates_tensor, atomic_numbers_tensor, r=2.5):
    """Creates a PyTorch Geometric graph."""
    if 'torch_cluster' not in sys.modules:
        return None # Skip if dependencies missing
    from torch_cluster import radius_graph
    from torch_geometric.data import Data
    
    edge_index = radius_graph(cartesian_coordinates_tensor, r=r)
    data = Data(x=atomic_numbers_tensor.view(-1, 1).float(), 
                pos=cartesian_coordinates_tensor, 
                edge_index=edge_index)
    return data

def correct_edges(data, scale_factor=1.3):
    """Corrects edges based on covalent radii."""
    if data is None: return None
    from ase.data import covalent_radii

    atomic_nums = data.x.view(-1).int().tolist()
    edge_index = data.edge_index
    valid_edges = []
    
    for node in range(len(atomic_nums)):
        adjacent_nodes = edge_index[1][edge_index[0] == node].tolist()
        for adj_node in adjacent_nodes:
            bond_length = torch.norm(data.pos[node] - data.pos[adj_node]).item()
            r1 = covalent_radii[atomic_nums[node]] * scale_factor
            r2 = covalent_radii[atomic_nums[adj_node]] * scale_factor
            if bond_length <= r1 + r2:
                valid_edges.append([node, adj_node])
                
    data.edge_index = torch.tensor(valid_edges, dtype=torch.long).t().contiguous()
    return data

def get_num_graphs(data):
    """Calculates number of connected components."""
    if data is None: return -1
    if data.edge_index.numel() == 0: return data.num_nodes
    g = to_networkx(data, to_undirected=True)
    return nx.number_connected_components(g)

def augment_distortion(
    input_source: Path, # dir or db
    output_target: Path, # dir or db
    sigma: float = 0.1, # d_max in original script
    fraction: float = 1.0,
    is_db_mode: bool = None,
    freeze_indices: List[int] = None
):
    """
    Applies random distortion to atomic coordinates.
    Also calculates graph connectivity.
    """
    d_max = sigma # Renaming to match original logic
    
    input_path = Path(input_source)
    if is_db_mode is None:
         is_db_mode = input_path.suffix == '.db'
         if is_db_mode:
             logger.info(f"Auto-detected DB mode from input: {input_path}")
         elif input_path.is_dir():
             logger.info(f"Auto-detected XYZ mode from input directory: {input_path}")
         else:
             # Fallback or error if ambiguous? 
             # If it's a file but not .db, it might be an XYZ file, but the logic below assumes dir for XYZ.
             # Original logic: input_dir.glob("*.xyz")
             pass
    
    if is_db_mode:
        db_path = Path(input_source)
        output_db_path = Path(output_target)
        
        db = connect(str(db_path))
        output_db = connect(str(output_db_path))
        num_entries = len(db)
        
        for row in tqdm(db.select(), total=num_entries, desc="Distorting molecules"):
            try:
                atoms = row.toatoms()
                coords = torch.tensor(atoms.get_positions(), dtype=torch.float32)
                
                d = random.uniform(0, d_max)
                offsets = (torch.rand_like(coords) * 2 - 1) * d
                
                if freeze_indices:
                     mask = torch.ones_like(coords)
                     valid_indices = [i for i in freeze_indices if i < len(coords)]
                     if valid_indices:
                         mask[valid_indices] = 0.0
                     offsets = offsets * mask
                     
                new_coords = coords + offsets
                
                distorted_atoms = atoms.copy()
                distorted_atoms.set_positions(new_coords.numpy())
                
                # Connectivity check
                num_graphs = -1
                if 'torch_geometric' in sys.modules:
                    z = torch.tensor(atoms.get_atomic_numbers(), dtype=torch.long)
                    data = create_pyg_graph(new_coords, z)
                    data = correct_edges(data)
                    num_graphs = get_num_graphs(data)

                new_data = row.data.copy()
                new_data['original_id'] = row.id
                new_data['distortion_d'] = d
                new_data['num_graph'] = num_graphs
                
                # We keep existing KVPs but ensures new ones go to 'data'
                output_db.write(atoms=distorted_atoms, key_value_pairs=row.key_value_pairs, data=new_data)
                
            except Exception as e:
                logger.error(f"Failed to process row {row.id}: {e}")
                
    else:
        # XYZ Mode
        input_dir = Path(input_source)
        output_dir = Path(output_target)
        output_dir.mkdir(exist_ok=True)
        
        files = sorted(list(input_dir.glob("*.xyz")))
        
        records = []
        for f in tqdm(files, desc="Distorting XYZs"):
            try:
                atoms, coords = read_xyz(f)
                coords = torch.tensor(coords, dtype=torch.float32)
                
                d = random.uniform(0, d_max)
                offsets = (torch.rand_like(coords) * 2 - 1) * d
                
                if freeze_indices:
                     mask = torch.ones_like(coords)
                     valid_indices = [i for i in freeze_indices if i < len(coords)]
                     if valid_indices:
                         mask[valid_indices] = 0.0
                     offsets = offsets * mask

                new_coords = coords + offsets
                
                # Connectivity check
                num_graphs = -1
                if 'torch_geometric' in sys.modules:
                    z = torch.tensor(symbols2numbers(atoms), dtype=torch.long)
                    data = create_pyg_graph(new_coords, z)
                    data = correct_edges(data)
                    num_graphs = get_num_graphs(data)
                
                out_name = f"{f.stem}_{d:.4f}.xyz"
                write_xyz(output_dir / out_name, atoms, new_coords.numpy())
                
                records.append({
                    'original': f.name,
                    'new': out_name,
                    'd': d,
                    'num_graphs': num_graphs
                })
            except Exception as e:
                logger.error(f"Failed {f}: {e}")
                
        # Save CSV
        import csv
        with open(output_dir / 'distortion_data.csv', 'w') as f:
            writer = csv.DictWriter(f, fieldnames=['original', 'new', 'd', 'num_graphs'])
            writer.writeheader()
            writer.writerows(records)


# --- Augmentation Logic: Size ---

from scipy.spatial.transform import Rotation
from collections import defaultdict
import math

def get_target_count(s, s_start, t_start, s_end, t_end, decay_power=1.0):
    if s < s_start: return t_start
    if s > s_end: return t_end
    
    if t_start <= 0 or t_end <= 0:
        return t_start + (t_end - t_start) * (s - s_start) / (s_end - s_start)
        
    log_t_start = math.log(t_start)
    log_t_end = math.log(t_end)
    interp = ((s - s_start) / (s_end - s_start)) ** (1.0 / decay_power)
    return math.exp(log_t_start + (log_t_end - log_t_start) * interp)

def augment_size(
    input_db: Path,
    output_db: Path,
    s_start: int, t_start: int,
    s_end: int, t_end: int,
    strength: float = 1.0,
    decay_power: float = 1.0,
    invert_prob: float = 0.5,
    plot_prefix: Path = None
):
    """
    Augments DB by adding rotated/inverted versions to balance molecule sizes.
    """
    from MolecularDiffusion.utils import plot_function as pf
    import matplotlib.pyplot as plt

    db = connect(str(input_db))
    counts = defaultdict(int)
    total = len(db)
    
    # Phase 1: Count
    for row in tqdm(db.select(), total=total, desc="Scanning sizes"):
        counts[row.natoms] += 1
        
    # Phase 2: Calculate Factors
    factors = {}
    for s in sorted(counts.keys()):
        if s_start <= s <= s_end:
            n_s = counts[s]
            if n_s == 0: continue
            
            t_s = get_target_count(s, s_start, t_start, s_end, t_end, decay_power)
            needed = (t_s - n_s) * strength
            target = n_s + needed
            
            if target > n_s:
                factor = math.floor(target / n_s) - 1
                if factor > 0: factors[s] = factor

    # Phase 3: Augment
    output_db = Path(output_db)
    if output_db.exists():
        logger.warning(f"Output DB {output_db} exists. Appending...")
        
    new_db = connect(str(output_db))
    
    if not factors:
        logger.info("No augmentation needed. Copying...")
        for row in tqdm(db.select(), total=total, desc="Copying"):
             new_db.write(row.toatoms(), key_value_pairs=row.key_value_pairs, data=row.data)
    else:
        for row in tqdm(db.select(), total=total, desc="Augmenting"):
            # Write original
            new_db.write(row.toatoms(), key_value_pairs=row.key_value_pairs, data=row.data)
            
            s = row.natoms
            if s in factors:
                factor = factors[s]
                atoms = row.toatoms()
                pos = atoms.get_positions()
                center = np.mean(pos, axis=0)
                pos -= center
                
                for _ in range(factor):
                    new_pos = pos.copy()
                    
                    # Random rotation
                    rot = Rotation.random().as_matrix()
                    new_pos = new_pos @ rot.T
                    
                    # Inversion
                    if random.random() < invert_prob:
                        new_pos *= -1.0
                        
                    new_pos += center
                    aug_atoms = atoms.copy()
                    aug_atoms.set_positions(new_pos)
                    
                    new_db.write(aug_atoms, key_value_pairs=row.key_value_pairs.copy(), data=row.data.copy())

    logger.info(f"Augmentation complete. New size: {len(new_db)}")
    
    # Plotting
    if plot_prefix:
        plot_prefix = str(plot_prefix)
        sizes = [row.natoms for row in new_db.select()]
        sizes = np.array(sizes)
        try:
             Path(plot_prefix).parent.mkdir(parents=True, exist_ok=True)
             pf.plot_histogram_distribution(sizes, task_name="num_atoms_augmented", output_path=f"{plot_prefix}_hist.png")
             pf.plot_kde_distribution(sizes, task_name="num_atoms_augmented", output_path=f"{plot_prefix}_kde.png")
        except Exception as e:
            logger.error(f"Failed to plot sizes: {e}")


