"""Tier-1 offline fidelity suite for the DiTMC port.

This is the **acceptance gate** for the integration, and it needs nothing
beyond what is already installed -- no jax, no flax, no e3x, no orbax.

The key enabler: e3x's spherical-harmonic and Clebsch-Gordan tables are
generated by pure SymPy (``so3/_symbolic.py`` imports only ``sympy`` and
``sympy.physics.wigner``), and SymPy is installed. So the ported tables are not
*approximated* -- :func:`test_tables_match_e3x_own_generator` re-runs e3x's own
generator and asserts elementwise equality.

What this suite does **not** cover, and cannot: bit-level parity against a
running JAX/Flax DiTMC, and reading the published Orbax checkpoints. Both need
an install that has not happened. Tier 1 proves the port is self-consistent and
mathematically correct; only Tier 2 proves it is *the same function* as
upstream.

Run::

    pytest tests/test_ditmc_e3x.py -q
"""

from __future__ import annotations

import importlib.util
import math
import os

import numpy as np
import pytest
import torch

from MolecularDiffusion.modules.layers import e3x
from MolecularDiffusion.modules.layers.e3x import features as e3x_features
from MolecularDiffusion.modules.layers.e3x import initializers as e3x_init
from MolecularDiffusion.modules.layers.e3x.modules import (
    Dense as E3Dense,
)
from MolecularDiffusion.modules.layers.e3x.modules import (
    SelfAttention,
    Tensor,
)
from MolecularDiffusion.modules.models.ditmc import (
    CondGraph,
    FlowMatching,
    LatentGraph,
    build_variant,
    kabsch_align,
)
from MolecularDiffusion.modules.models.ditmc.flow_matching import aggregate_node_error
from MolecularDiffusion.modules.models.ditmc.graph_features import (
    UNREACHABLE_HOPS,
    all_pairs_edges,
    laplacian_eigen,
    shortest_hops_from_adjacency,
)
from MolecularDiffusion.modules.models.ditmc.layers import EquivariantLayerNorm
from MolecularDiffusion.modules.models.ditmc.priors import HarmonicPrior
from MolecularDiffusion.modules.models.ditmc.graphs import PriorGraph

DTYPE = torch.float64


# ---------------------------------------------------------------- SH and CG


def test_spherical_harmonics_hard_coded_ground_truth():
    """The plan's literal ground truth for a unit vector ``(x, y, z)``.

    Degree 1 must be ``(x, y, z)`` -- Cartesian order ``m = +l, -l, ..., 0``.
    An m-ascending convention (e3nn's) would give ``(y, z, x)``.
    """
    torch.manual_seed(0)
    r = torch.randn(128, 3, dtype=DTYPE)
    u = r / r.norm(dim=-1, keepdim=True)
    y = e3x.spherical_harmonics(u, 2)
    x, yy, z = u[:, 0], u[:, 1], u[:, 2]
    expect = torch.stack(
        [
            torch.ones_like(x),
            x,
            yy,
            z,
            math.sqrt(3) / 2 * (x**2 - yy**2),
            math.sqrt(3) * x * yy,
            math.sqrt(3) * x * z,
            math.sqrt(3) * yy * z,
            (3 * z**2 - 1) / 2,
        ],
        dim=-1,
    )
    assert torch.allclose(y, expect, atol=1e-12)


def test_cartesian_permutation():
    assert list(e3x.cartesian_permutation_for_degree(0)) == [0]
    assert list(e3x.cartesian_permutation_for_degree(1)) == [2, 0, 1]
    assert list(e3x.cartesian_permutation_for_degree(2)) == [4, 0, 3, 1, 2]


def test_clebsch_gordan_identity_and_selection_rule():
    cg = e3x.clebsch_gordan(1, 1, 1, dtype=DTYPE)
    assert cg[0, 0, 0].item() == pytest.approx(1.0, abs=1e-12)
    cg2 = e3x.clebsch_gordan(2, 2, 2, dtype=DTYPE)
    # Zero wherever the triangle rule is violated.
    for l1 in range(3):
        for l2 in range(3):
            for l3 in range(3):
                if not abs(l1 - l2) <= l3 <= l1 + l2:
                    block = cg2[
                        l1**2 : (l1 + 1) ** 2,
                        l2**2 : (l2 + 1) ** 2,
                        l3**2 : (l3 + 1) ** 2,
                    ]
                    assert block.abs().max().item() == pytest.approx(0.0, abs=1e-12)


def _e3x_symbolic_module():
    """Load the vendored e3x SymPy generator from the reference cache."""
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(
        here,
        "..",
        "docs",
        "model_integrations",
        "ditmc",
        "reference",
        "e3x_source",
        "so3",
        "_symbolic.py",
    )
    path = os.path.realpath(path)
    if not os.path.exists(path):
        pytest.skip(f"e3x reference source not present at {path}")
    spec = importlib.util.spec_from_file_location("_e3x_symbolic", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_tables_match_e3x_own_generator():
    """Re-run e3x's generator and compare EXACTLY, not approximately."""
    sympy = pytest.importorskip("sympy")
    sym = _e3x_symbolic_module()

    # Spherical harmonics: evaluate e3x's symbolic polynomial and the port at
    # the same random points.
    torch.manual_seed(1)
    r = torch.randn(24, 3, dtype=DTYPE)
    u = (r / r.norm(dim=-1, keepdim=True)).numpy()
    ours = e3x.spherical_harmonics(torch.as_tensor(u), 2).numpy()

    x, y, z = sympy.symbols("x y z")
    for l in range(3):  # noqa: E741
        perm = e3x.cartesian_permutation_for_degree(l)
        for slot, m_idx in enumerate(perm):
            m = int(m_idx) - l
            poly = sym._spherical_harmonics(l, m)
            f = sympy.lambdify((x, y, z), poly.as_expr(), "numpy")
            ref = f(u[:, 0], u[:, 1], u[:, 2])
            ref = np.broadcast_to(np.asarray(ref, dtype=np.float64), (u.shape[0],))
            got = ours[:, l**2 + slot]
            assert np.allclose(got, ref, atol=1e-12), (l, m, np.abs(got - ref).max())

    # Clebsch-Gordan: regenerate and assert elementwise equality.
    ours_cg = e3x.clebsch_gordan(1, 1, 1, dtype=DTYPE).numpy()
    for l1 in range(2):
        for l2 in range(2):
            for l3 in range(2):
                p1 = e3x.cartesian_permutation_for_degree(l1)
                p2 = e3x.cartesian_permutation_for_degree(l2)
                p3 = e3x.cartesian_permutation_for_degree(l3)
                for a, ma in enumerate(p1):
                    for b, mb in enumerate(p2):
                        for c, mc in enumerate(p3):
                            ref = float(
                                sym._clebsch_gordan(
                                    l1, int(ma) - l1, l2, int(mb) - l2, l3, int(mc) - l3
                                )
                            )
                            got = ours_cg[l1**2 + a, l2**2 + b, l3**2 + c]
                            assert got == pytest.approx(ref, abs=1e-12), (
                                l1, l2, l3, a, b, c, got, ref,
                            )


def _fit_wigner_d(rot: torch.Tensor, degree: int) -> torch.Tensor:
    """Least-squares Wigner-D for one degree, from the ported SH themselves.

    ponytail: e3x's own ``wigner_d`` needs a second symbolic lookup table this
    port has no other use for. Fitting D from SH values at more points than
    unknowns is an equally strong check -- an inconsistent representation
    simply will not fit. Upgrade to the real table only if a future model needs
    ``wigner_d`` at runtime.
    """
    n = 2 * degree + 1
    u = torch.randn(64, 3, dtype=DTYPE)
    u = u / u.norm(dim=-1, keepdim=True)
    y = e3x.spherical_harmonics(u, degree)[:, degree**2 :]
    y_rot = e3x.spherical_harmonics(u @ rot.T, degree)[:, degree**2 :]
    d = torch.linalg.lstsq(y, y_rot).solution.T
    assert (y @ d.T - y_rot).abs().max() < 1e-9, "SH do not form a representation"
    assert d.shape == (n, n)
    return d


def test_spherical_harmonics_are_a_rotation_representation():
    torch.manual_seed(2)
    for _ in range(3):
        rot = e3x.random_rotation(1, dtype=DTYPE)[0]
        d1 = _fit_wigner_d(rot, 1)
        # Degree 1 in Cartesian order IS the rotation matrix.
        assert torch.allclose(d1, rot, atol=1e-9), (d1 - rot).abs().max()
        d2 = _fit_wigner_d(rot, 2)
        eye = torch.eye(5, dtype=DTYPE)
        assert torch.allclose(d2 @ d2.T, eye, atol=1e-8)


# ------------------------------------------------------------- e3x plumbing


def test_add_and_change_max_degree_zero_fill():
    torch.manual_seed(3)
    for (p_in, l_in), (p_out, l_out) in [
        ((1, 0), (1, 1)),
        ((1, 0), (2, 1)),
        ((1, 1), (2, 1)),
        ((2, 1), (1, 1)),
        ((2, 1), (2, 0)),
    ]:
        x = torch.randn(5, p_in, (l_in + 1) ** 2, 7, dtype=DTYPE)
        y = e3x.change_max_degree_or_type(
            x, max_degree=l_out, include_pseudotensors=p_out == 2
        )
        assert y.shape == (5, p_out, (l_out + 1) ** 2, 7)
        if p_out == 2 and p_in == 1:
            # degree l lands only in the parity block l % 2; the rest is zero.
            for l in range(min(l_in, l_out) + 1):  # noqa: E741
                blk = y[:, 1 - l % 2, l**2 : (l + 1) ** 2, :]
                assert blk.abs().max() == 0

    a = torch.randn(5, 1, 1, 7, dtype=DTYPE)
    b = torch.randn(5, 2, 4, 7, dtype=DTYPE)
    s = e3x.add(a, b)
    assert s.shape == (5, 2, 4, 7)
    assert torch.allclose(s[:, 0, 0, :], a[:, 0, 0, :] + b[:, 0, 0, :])
    assert torch.allclose(s[:, 1, 0, :], b[:, 1, 0, :])  # a contributes nothing

    with pytest.raises(ValueError):
        e3x.add(a, torch.randn(5, 1, 1, 8, dtype=DTYPE))  # feature mismatch


def test_reflect_negates_odd_parity():
    torch.manual_seed(4)
    x2 = torch.randn(3, 2, 4, 5, dtype=DTYPE)
    r2 = e3x_features.reflect(x2)
    assert torch.allclose(r2[:, 0], x2[:, 0])
    assert torch.allclose(r2[:, 1], -x2[:, 1])

    x1 = torch.randn(3, 1, 4, 5, dtype=DTYPE)
    r1 = e3x_features.reflect(x1)
    assert torch.allclose(r1[:, 0, 0], x1[:, 0, 0])  # l=0 even
    assert torch.allclose(r1[:, 0, 1:4], -x1[:, 0, 1:4])  # l=1 odd


def test_gated_gelu_matches_tanh_approximation():
    """``e3x.nn.gelu`` on a scalar input is elementwise ``gelu(tanh)``."""
    torch.manual_seed(5)
    x = torch.randn(9, 1, 1, 6, dtype=DTYPE)
    got = e3x.gelu(x)
    ref = torch.nn.functional.gelu(x, approximate="tanh")
    assert torch.allclose(got, ref, atol=1e-12)
    # NOT the exact erf form -- that is the trap.
    assert not torch.allclose(got, torch.nn.functional.gelu(x), atol=1e-6)

    # On an L=1 input the l=1 block is scaled by the l=0-derived gate.
    y = torch.randn(9, 1, 4, 6, dtype=DTYPE)
    gated = e3x.gelu(y)
    gate = gated[:, 0:1, 0:1, :] / y[:, 0:1, 0:1, :]
    assert torch.allclose(gated[:, :, 1:4, :], gate * y[:, :, 1:4, :], atol=1e-12)


def test_reciprocal_bernstein_and_fourier():
    x = torch.linspace(0.0, 8.0, 200, dtype=DTYPE)
    b = e3x.reciprocal_bernstein(x, 16)
    assert torch.allclose(b.sum(-1), torch.ones_like(x), atol=1e-10)  # partition
    assert e3x.reciprocal_mapping(torch.zeros(1, dtype=DTYPE)).item() == 1.0
    assert b[0, 0].item() == pytest.approx(1.0, abs=1e-12)  # x=0 -> t=0
    f = e3x.basic_fourier(x, 5, limit=1.0)
    assert torch.allclose(f[:, 0], torch.ones_like(x))  # channel 0 is constant 1


def test_basis_axis_order():
    """Angular on axis -2, radial on axis -1. Transposing these is silent."""
    torch.manual_seed(6)
    r = torch.randn(11, 3, dtype=DTYPE)
    b = e3x.basis(
        r, max_degree=1, num=7, radial_fn=e3x.reciprocal_bernstein, cutoff_fn=None
    )
    assert b.shape == (11, 1, 4, 7)
    norm = r.norm(dim=-1, keepdim=True)
    u = r / norm
    ylm = e3x.spherical_harmonics(u, 1)
    rbf = e3x.reciprocal_bernstein(norm.squeeze(-1), 7)
    assert torch.allclose(b[:, 0], ylm[..., None] * rbf[..., None, :], atol=1e-12)


def test_lecun_normal_is_truncated():
    w = torch.empty(4096, 64, dtype=DTYPE)
    e3x_init.lecun_normal_(w, fan_in=64)
    std = math.sqrt(1 / 64) / e3x_init.TRUNCATED_NORMAL_STDDEV
    assert w.abs().max().item() <= 2 * std + 1e-9  # hard truncation
    assert w.std().item() == pytest.approx(math.sqrt(1 / 64), rel=0.05)


def test_tensor_lecun_normal_masks_forbidden_paths():
    shape = (1, 2, 1, 2, 2, 2, 8)
    k = torch.empty(shape, dtype=DTYPE)
    e3x_init.tensor_lecun_normal_(k)
    _fan_in, _fan_out, mask = e3x_init.compute_tensor_fans_and_mask(shape)
    assert (k[~torch.as_tensor(mask)] == 0).all()
    assert (k[torch.as_tensor(mask)] != 0).any()


# ------------------------------------------------------------- attention


def _self_edges(n: int):
    return all_pairs_edges(n)


def test_self_attention_reduces_to_plain_mha():
    """Pins ``1/sqrt(depth)`` and the ``f % num_heads`` q/k head fold."""
    torch.manual_seed(7)
    n, f, h = 6, 16, 4
    sa = SelfAttention(
        in_features=f,
        in_max_degree=0,
        in_num_parity=1,
        num_heads=h,
        max_degree=0,
        include_pseudotensors=False,
        use_relative_positional_encoding_qk=False,
        use_relative_positional_encoding_v=False,
    ).to(DTYPE)
    x = torch.randn(n, 1, 1, f, dtype=DTYPE)
    dst, src = _self_edges(n)
    out = sa(x, None, dst_idx=dst, src_idx=src, num_segments=n)

    q = sa.query(x).squeeze(1).squeeze(1)
    k = sa.key(x).squeeze(1).squeeze(1)
    v = sa.value(x).squeeze(1).squeeze(1)
    hd = f // h
    qh = q.reshape(n, hd, h).permute(2, 0, 1)
    kh = k.reshape(n, hd, h).permute(2, 0, 1)
    logits = (qh @ kh.transpose(1, 2)) / math.sqrt(hd)
    logits = logits.masked_fill(torch.eye(n, dtype=torch.bool), float("-inf"))
    w = torch.softmax(logits, dim=-1)
    # value feature f is weighted by head f // head_dim -- the OTHER fold
    vg = v.reshape(n, h, hd)
    ref = sa.out(torch.einsum("hij,jhd->ihd", w, vg).reshape(n, f)[:, None, None, :])
    assert torch.allclose(out, ref, atol=1e-11), (out - ref).abs().max()


def test_tensor_is_not_identity_at_max_degree_zero():
    """A learnable per-feature gate, initialized ~1.1368 -- not 1.0."""
    torch.manual_seed(8)
    t = Tensor(
        features=64,
        max_degree1=0,
        num_parity1=1,
        max_degree2=0,
        num_parity2=1,
        max_degree=0,
        include_pseudotensors=False,
    ).to(DTYPE)
    assert tuple(t.kernel.shape) == (1, 1, 1, 1, 1, 1, 64)
    assert t.kernel.std().item() == pytest.approx(1.0, rel=0.25)
    a = torch.randn(5, 1, 1, 64, dtype=DTYPE)
    b = torch.randn(5, 1, 1, 64, dtype=DTYPE)
    got = t(a, b)
    assert torch.allclose(got, t.kernel.reshape(1, 1, 1, 64) * a * b, atol=1e-12)


def test_self_attention_is_so3_equivariant():
    """Rotating the geometry rotates the l=1 block and leaves l=0 invariant."""
    torch.manual_seed(9)
    n, f, nb = 6, 16, 8
    sa = SelfAttention(
        in_features=f,
        in_max_degree=0,
        in_num_parity=1,
        num_heads=4,
        max_degree=1,
        include_pseudotensors=True,
        num_basis=nb,
        basis_max_degree=1,
        basis_num_parity=1,
    ).to(DTYPE)
    x = torch.randn(n, 1, 1, f, dtype=DTYPE)
    pos = torch.randn(n, 3, dtype=DTYPE)
    dst, src = _self_edges(n)

    def run(p):
        b = e3x.basis(
            p[src] - p[dst],
            max_degree=1,
            num=nb,
            radial_fn=e3x.reciprocal_bernstein,
            cutoff_fn=None,
        )
        return sa(x, b, dst_idx=dst, src_idx=src, num_segments=n)

    out = run(pos)
    rot = e3x.random_rotation(1, dtype=DTYPE)[0]
    out_r = run(pos @ rot.T)
    assert torch.allclose(out_r[..., 0, :], out[..., 0, :], atol=1e-10)
    vec = out[..., 1:4, :]
    vec_r = out_r[..., 1:4, :]
    assert torch.allclose(vec_r, torch.einsum("ij,npjf->npif", rot, vec), atol=1e-10)


def test_equivariant_layer_norm():
    torch.manual_seed(10)
    # At P=1, L=0 it is a plain LayerNorm.
    ln = EquivariantLayerNorm(8, 0, 1).to(DTYPE)
    x = torch.randn(5, 1, 1, 8, dtype=DTYPE)
    ref = torch.nn.functional.layer_norm(x, (8,), ln.norm00.weight, ln.norm00.bias, 1e-6)
    assert torch.allclose(ln(x), ref, atol=1e-12)

    # At L=1 the l>0 scaling is rotation invariant.
    ln1 = EquivariantLayerNorm(8, 1, 1, use_scale=False, use_bias=False).to(DTYPE)
    y = torch.randn(5, 1, 4, 8, dtype=DTYPE)
    rot = e3x.random_rotation(1, dtype=DTYPE)[0]
    y_r = y.clone()
    y_r[:, 0, 1:4, :] = torch.einsum("ij,njf->nif", rot, y[:, 0, 1:4, :])
    out, out_r = ln1(y), ln1(y_r)
    assert torch.allclose(out[:, 0, 0], out_r[:, 0, 0], atol=1e-11)
    assert torch.allclose(
        torch.einsum("ij,njf->nif", rot, out[:, 0, 1:4]), out_r[:, 0, 1:4], atol=1e-11
    )


# ------------------------------------------------------------- whole model


def _toy_graphs(n=6, a=64, seed=11):
    torch.manual_seed(seed)
    dst, src = all_pairs_edges(n)
    e = src.shape[0]
    latent = LatentGraph(
        atomic_numbers=torch.tensor([6, 1, 1, 8, 1, 7]),
        node_attr=torch.randn(n, a, dtype=DTYPE),
        positions=torch.randn(n, 3, dtype=DTYPE),
        senders=src,
        receivers=dst,
        shortest_hops=torch.randint(0, 4, (e,)),
        batch_segments=torch.zeros(n, dtype=torch.long),
        num_graphs=1,
        cond_scaling_nodes=torch.ones(n, dtype=DTYPE),
        cond_scaling_edges=torch.ones(e, dtype=DTYPE),
    )
    cond = CondGraph(
        node_attr=latent.node_attr,
        senders=torch.tensor([0, 1, 0, 3]),
        receivers=torch.tensor([1, 0, 3, 0]),
        edge_attr=torch.eye(4, dtype=DTYPE),
    )
    return latent, cond


_SMALL = dict(
    num_layers=2,
    num_heads=4,
    num_features_head=8,
    mgn_num_features=32,
    mgn_num_layers=1,
    num_features_mlp=64,
    num_radial_basis=8,
)


def _build(variant, self_conditioning=False):
    return build_variant(
        variant,
        node_attr_dim=64,
        self_conditioning_bool=self_conditioning,
        **_SMALL,
    ).to(DTYPE)


def test_adaln_zero_denses_are_zero_initialized():
    """Every adaLN-Zero Dense starts at exactly zero.

    A loaded checkpoint would hide a mistake here; training from scratch would
    not. The zero-init modules are: each DiT block's modulation Dense, and the
    readout's. ``MLP(output_is_zero_at_init=True)`` in
    ``RadialSphericalEdgeEmbedding`` is checked too.
    """
    for variant in ("ape", "rpe", "so3"):
        model = _build(variant)
        for layer in model.layers:
            assert layer.ada_dense.weight.abs().max().item() == 0.0, variant
            assert layer.ada_dense.bias.abs().max().item() == 0.0, variant
        assert model.readout.ada_dense.weight.abs().max().item() == 0.0, variant
        if variant == "so3":
            last = model.edge_embedding.hops_mlp.layers[-1]
            assert last.weight.abs().max().item() == 0.0


def test_so3_drift_is_exactly_zero_at_init():
    """adaLN-Zero leaves dit_so3 with no l=1 signal at all at init.

    Exactly 0.0, not small: the equivariant readout reads only the ``l=1``
    block, and every residual branch that could populate it is gated by a
    zero-initialized alpha. ``dit_ape``/``dit_rpe`` are deliberately NOT
    included -- their readout head maps the (non-zero) invariant node features
    straight to a drift, so theirs is non-zero at init by construction.
    """
    latent, cond = _toy_graphs()
    t = torch.full((latent.num_nodes,), 0.3, dtype=DTYPE)
    drift, noise = _build("so3")(time_latent=t, graph_latent=latent, graph_cond=cond)
    assert drift.abs().max().item() == 0.0
    assert noise.abs().max().item() == 0.0


def _randomize_zero_init(model):
    with torch.no_grad():
        for p in model.parameters():
            if p.abs().max() == 0:
                p.normal_(0, 0.3)
    return model


def test_dit_so3_forward_is_so3_equivariant():
    """The single strongest end-to-end offline check."""
    latent, cond = _toy_graphs()
    t = torch.full((latent.num_nodes,), 0.37, dtype=DTYPE)
    model = _randomize_zero_init(_build("so3"))
    drift, _ = model(time_latent=t, graph_latent=latent, graph_cond=cond)
    assert drift.abs().max() > 1e-3, "test is vacuous if the drift is zero"
    rot = e3x.random_rotation(1, dtype=DTYPE)[0]
    drift_r, _ = model(
        time_latent=t,
        graph_latent=latent.replace(positions=latent.positions @ rot.T),
        graph_cond=cond,
    )
    assert torch.allclose(drift_r, drift @ rot.T, atol=1e-10), (
        (drift_r - drift @ rot.T).abs().max()
    )


@pytest.mark.parametrize("variant", ["ape", "rpe"])
def test_dit_ape_rpe_are_not_equivariant_but_are_permutation_equivariant(variant):
    latent, cond = _toy_graphs()
    t = torch.full((latent.num_nodes,), 0.37, dtype=DTYPE)
    model = _randomize_zero_init(_build(variant))
    drift, _ = model(time_latent=t, graph_latent=latent, graph_cond=cond)
    rot = e3x.random_rotation(1, dtype=DTYPE)[0]
    drift_r, _ = model(
        time_latent=t,
        graph_latent=latent.replace(positions=latent.positions @ rot.T),
        graph_cond=cond,
    )
    # These variants are NOT equivariant by construction. Asserting so keeps
    # someone from "fixing" them into something the weights do not describe.
    assert not torch.allclose(drift_r, drift @ rot.T, atol=1e-3)


# ------------------------------------------------------------ data plumbing


def test_shortest_hops_match_scipy_and_the_edge_order():
    scipy_csgraph = pytest.importorskip("scipy.sparse.csgraph")
    rng = np.random.default_rng(0)
    for n in (2, 5, 9):
        adj = (rng.random((n, n)) < 0.35).astype(np.int64)
        adj = np.triu(adj, 1)
        adj = adj + adj.T
        hops = shortest_hops_from_adjacency(adj)
        dist = scipy_csgraph.floyd_warshall(
            adj.astype(float), directed=False, unweighted=True
        )
        rec, sen = all_pairs_edges(n)
        assert len(hops) == n * (n - 1)
        for k in range(len(hops)):
            ref = dist[rec[k], sen[k]]
            ref = UNREACHABLE_HOPS if np.isinf(ref) else ref
            assert hops[k] == ref, (n, k)


def test_harmonic_prior_covariance_is_the_laplacian_pseudoinverse():
    adj = np.array(
        [[0, 1, 0, 0], [1, 0, 1, 0], [0, 1, 0, 1], [0, 0, 1, 0]], dtype=np.int64
    )
    d, p = laplacian_eigen(adj, num_components=1)
    n = 4
    i, j = torch.meshgrid(torch.arange(n), torch.arange(n), indexing="ij")
    graph = PriorGraph(
        node_attr=torch.as_tensor(d),
        senders=j.reshape(-1),
        receivers=i.reshape(-1),
        edge_attr=torch.as_tensor(p).reshape(-1),
    )
    g = torch.Generator().manual_seed(0)
    s = torch.stack(
        [HarmonicPrior().sample((n, 3), graph, generator=g) for _ in range(20000)]
    )
    cov = torch.einsum("sid,sjd->ij", s, s) / (s.shape[0] * 3)
    lap = np.diag(adj.sum(1)) - adj
    expect = torch.as_tensor(np.linalg.pinv(lap.astype(float)), dtype=torch.float32)
    assert torch.allclose(cov, expect, atol=0.08)
    # The lambda=0 mode is zeroed, which is what removes the COM.
    assert s.mean(dim=1).abs().max() < 1e-4


def test_kabsch_alignment():
    torch.manual_seed(12)
    segments = torch.tensor([0, 0, 0, 1, 1, 1])
    q = torch.randn(6, 3, dtype=DTYPE)
    rot = e3x.random_rotation(2, dtype=DTYPE)
    assert torch.allclose(torch.linalg.det(rot), torch.ones(2, dtype=DTYPE), atol=1e-10)
    p = torch.einsum(
        "bij,bj->bi", rot.index_select(0, segments), q
    ) + torch.tensor([1.0, -2.0, 3.0], dtype=DTYPE)
    aligned = kabsch_align(p, q, segments, 2)
    assert (aligned - q).abs().max() < 1e-8


def test_loss_reduction_is_mean_over_xyz_and_atoms():
    """A sum over xyz would scale the loss by 3N; a sum over atoms by N."""
    segments = torch.tensor([0, 0, 0, 1, 1])
    err = torch.full((5, 3), 4.0, dtype=DTYPE)
    assert aggregate_node_error(err, segments, 2).item() == pytest.approx(4.0)
    w = torch.tensor([2.0, 0.0], dtype=DTYPE)
    assert aggregate_node_error(err, segments, 2, graph_weight=w).item() == (
        pytest.approx(4.0)
    )


def test_regress_x1_drift_identity():
    fm = FlowMatching(prior=None)
    latent, _ = _toy_graphs(n=5)
    tau = torch.full((5,), 0.25, dtype=DTYPE)
    out = torch.randn(5, 3, dtype=DTYPE)
    x1_pred, vt = fm.clean_prediction(out, latent, tau)
    assert torch.allclose(vt, (x1_pred - latent.positions) / 0.75, atol=1e-12)


def test_cfg_scaling_gates_exactly_what_upstream_gates():
    """``cond_scaling = 0`` gates the conditioner and the shortest-hops term.

    Which pieces survive is variant-specific and worth pinning, because it is
    not symmetric:

    * ``ape`` -- the edge embedding has NO displacement term, so gating the
      hops term leaves it identically zero.
    * ``rpe`` -- the displacement MLP is ungated, so the edge embedding stays
      non-zero.
    * ``so3`` -- the spherical basis is ungated; only the learned hops
      scaling is gated.

    Note also the readout quirk this reproduces: neither ``SimpleReadout`` nor
    ``EquivariantReadout`` applies ``cond_scaling``, so the conditioner
    features reach the readout unscaled even when every DiT block has them
    zeroed. That is upstream behaviour, quirk and all.
    """
    latent, cond = _toy_graphs()
    e = latent.senders.shape[0]
    off = latent.replace(
        cond_scaling_nodes=torch.zeros(latent.num_nodes, dtype=DTYPE),
        cond_scaling_edges=torch.zeros(e, dtype=DTYPE),
    )
    expect_zero = {"ape": True, "rpe": False, "so3": False}
    for variant in ("ape", "rpe", "so3"):
        model = _randomize_zero_init(_build(variant))
        on = model.edge_embedding(latent)
        gated = model.edge_embedding(off)
        assert not torch.allclose(on, gated), variant
        if expect_zero[variant]:
            assert gated.abs().max().item() == 0.0, variant
        else:
            assert gated.abs().max().item() > 0.0, variant

        t = torch.full((latent.num_nodes,), 0.4, dtype=DTYPE)
        d_on, _ = model(time_latent=t, graph_latent=latent, graph_cond=cond)
        d_off, _ = model(time_latent=t, graph_latent=off, graph_cond=cond)
        assert not torch.allclose(d_on, d_off, atol=1e-6), variant


def test_guidance_scale_one_reproduces_the_unguided_update():
    """CFG at scale 1.0 must be a bit-for-bit no-op."""
    latent, cond = _toy_graphs()
    prior = HarmonicPrior()
    n = latent.num_nodes
    i, j = torch.meshgrid(torch.arange(n), torch.arange(n), indexing="ij")
    graph_prior = PriorGraph(
        node_attr=torch.ones(n, dtype=DTYPE),
        senders=j.reshape(-1),
        receivers=i.reshape(-1),
        edge_attr=torch.eye(n, dtype=DTYPE).reshape(-1),
    )
    model = _randomize_zero_init(_build("so3"))

    def run(free_guidance):
        fm = FlowMatching(prior=prior, free_guidance_bool=free_guidance)
        g = torch.Generator().manual_seed(3)
        out = fm.sample(
            model, latent, graph_prior, cond, num_steps=3, generator=g,
            free_guidance_scale=1.0,
        )
        return out.positions

    assert torch.allclose(run(False), run(True), atol=1e-11)


def test_self_conditioning_starts_from_zeros_and_does_not_leak_gradient():
    latent, cond = _toy_graphs()
    model = _build("so3", self_conditioning=True)
    emb = model.node_embedding
    assert emb.sc_mlp is not None
    zeros = latent.replace(self_cond=torch.zeros(latent.num_nodes, 3, dtype=DTYPE))
    # step 0 uses zeros: passing None must be identical to passing zeros.
    assert torch.allclose(emb(latent), emb(zeros), atol=1e-12)
    # the MLP is bias-free, so a zero self_cond contributes exactly nothing
    assert all(layer.bias is None for layer in emb.sc_mlp.layers)


def test_parameter_count_of_the_shipped_so3_model():
    """A tripwire on the shipped hyperparameters, not a claim about upstream.

    Upstream's parameter count cannot be read without JAX (Tier 2). What this
    pins is that nobody silently changes the shipped defaults -- 6 layers x 8
    heads x 32 features/head plus a 2-layer 256-feature MeshGraphNet.
    """
    m = build_variant("so3", node_attr_dim=64)
    n = sum(p.numel() for p in m.parameters())
    assert 5_000_000 < n < 60_000_000, n
