_target_: MolecularDiffusion.runmodes.generate.GenerativeFactory
task_type: outpaint
sampling_mode: "ddpm"
num_generate: 100
mol_size:  [0,0]
target_values: []
property_names: []
batch_size: 1
seed: 86
n_frames: 0
output_path: generated_mol
condition_configs:
  reference_structure_path: "data/template_structures/BINOLCp.xyz"
  condition_component: xh
  outpaint_cfgs:
    t_start: 0.8
    constraint_strength: 0.7  # Apply constraints for s < this value (0–1). Bonding
                               # constraints (enforce + intact) active for s > value/2.
    scale_factor: 1.1          # Multiplier on covalent radii for bond-distance tolerance.
    noise_initial_mask: False
    connector_dicts:
  n_retrys: 3
  t_retry: 180

