# This file represents the combined configuration for inpainting generation.
# In the actual project, this is composed from `configs/generate.yaml` and `configs/interference/my_inpaint.yaml`.

defaults:
  - tasks: diffusion
  - interference: gen_inpaint
  - _self_

name: "akatsuki"
chkpt_directory: "models/edm_pretrained/"
atom_vocab: [H,B,C,N,O,F,Al,Si,P,S,Cl,As,Se,Br,I,Hg,Bi]
diffusion_steps: 600
seed: 9

interference:
  _target_: MolecularDiffusion.runmodes.generate.GenerativeFactory
  task_type: inpaint
  sampling_mode: "ddpm"
  num_generate: 50
  mol_size: [50, 60] # Target size of the generated molecule
  output_path: "results/my_inpainting_run"
  condition_configs:
    reference_structure_path: "assets/BINOLCpHHH.xyz" # path the to reference structure
    condition_component: xh # component to inpaint (available choice: x, h, xh)
    inpaint_cfgs:
      # To vary the BINOL part of the molecule, we mask the following 0-indexed atoms:
      mask_node_index: [5, 30, 31, 6, 7, 45, 8, 32, 9, 10, 33, 11, 34, 12, 35, 13, 36, 14, 15, 16, 17, 18, 37, 19, 38, 20, 39, 21, 40, 22, 23, 41, 24, 44, 25, 26, 43, 42]
      denoising_strength: 0.5

      # constraint setting
      t_start: 0.8
      t_critical_1: 0.8
      t_critical_2: 0.6
      d_threshold_f: 1.5
      w_b: 10
      all_frozen: True
      use_covalent_radii: True
      scale_factor: 0.8
      noise_initial_mask: True
    n_frames: 0
    n_retrys: 0
    t_retry: 180


