"""Reference bond-length tables, vendored verbatim from DiffSMol.

``others/DiffSMol/source/utils/analyze.py`` ``bonds1..bonds4`` (single /
double / triple / aromatic, in 0.01 A units, ``-1`` = "no such bond order
for this pair").

These are **not** interchangeable with the platform's own
``utils.geom_analyzer.bonds{1,2,3}``: 26 entries of ``bonds1`` and one of
``bonds2`` differ numerically (mostly Br/I pairs, plus ``S-C`` double).
Those tables drive the 5-class edge feature that every attention layer sees,
so the pretrained DiffSMol checkpoint only reproduces upstream's numbers
against *these* values. The element-vocab path built before this module
existed keeps using the platform tables and is untouched.
"""

from __future__ import annotations

BONDS_SINGLE: dict[str, dict[str, int]] = {'H': {'H': 74,
       'C': 109,
       'N': 101,
       'O': 96,
       'F': 92,
       'P': 144,
       'S': 134,
       'Cl': 127,
       'Br': 141,
       'I': 161},
 'C': {'H': 109,
       'C': 154,
       'N': 147,
       'O': 143,
       'F': 135,
       'P': 184,
       'S': 182,
       'Cl': 177,
       'Br': 194,
       'I': 214},
 'N': {'H': 101,
       'C': 147,
       'N': 145,
       'O': 140,
       'F': 136,
       'P': 177,
       'S': 168,
       'Cl': 175,
       'Br': -1,
       'I': -1},
 'O': {'H': 96,
       'C': 143,
       'N': 140,
       'O': 148,
       'F': 142,
       'P': 163,
       'S': 151,
       'Cl': 164,
       'Br': -1,
       'I': -1},
 'F': {'H': 92,
       'C': 135,
       'N': 136,
       'O': 142,
       'F': 142,
       'P': 156,
       'S': 158,
       'Cl': 166,
       'Br': -1,
       'I': 191},
 'P': {'H': 144,
       'C': 184,
       'N': 177,
       'O': 163,
       'F': 156,
       'P': 221,
       'S': 210,
       'Cl': 203,
       'Br': -1,
       'I': -1},
 'S': {'H': 134,
       'C': 182,
       'N': 168,
       'O': 151,
       'F': 158,
       'P': 210,
       'S': 204,
       'Cl': 207,
       'Br': -1,
       'I': -1},
 'Cl': {'H': 127,
        'C': 177,
        'N': 175,
        'O': 164,
        'F': 166,
        'P': 203,
        'S': 207,
        'Cl': 199,
        'Br': -1,
        'I': 232},
 'Br': {'H': 141,
        'C': 194,
        'N': -1,
        'O': -1,
        'F': -1,
        'P': -1,
        'S': -1,
        'Cl': -1,
        'Br': 228,
        'I': -1},
 'I': {'H': 161,
       'C': 214,
       'N': -1,
       'O': -1,
       'F': 191,
       'P': -1,
       'S': -1,
       'Cl': 232,
       'Br': -1,
       'I': 267}}

BONDS_DOUBLE: dict[str, dict[str, int]] = {'H': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'C': {'H': -1,
       'C': 134,
       'N': 129,
       'O': 120,
       'F': -1,
       'P': -1,
       'S': 160,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'N': {'H': -1,
       'C': 129,
       'N': 125,
       'O': 121,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'O': {'H': -1,
       'C': 120,
       'N': 121,
       'O': 121,
       'F': -1,
       'P': 150,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'F': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'P': {'H': -1,
       'C': -1,
       'N': -1,
       'O': 150,
       'F': -1,
       'P': -1,
       'S': 186,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'S': {'H': -1,
       'C': 160,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': 186,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'Cl': {'H': -1,
        'C': -1,
        'N': -1,
        'O': -1,
        'F': -1,
        'P': -1,
        'S': -1,
        'Cl': -1,
        'Br': -1,
        'I': -1},
 'Br': {'H': -1,
        'C': -1,
        'N': -1,
        'O': -1,
        'F': -1,
        'P': -1,
        'S': -1,
        'Cl': -1,
        'Br': -1,
        'I': -1},
 'I': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1}}

BONDS_TRIPLE: dict[str, dict[str, int]] = {'H': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'C': {'H': -1,
       'C': 120,
       'N': 116,
       'O': 113,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'N': {'H': -1,
       'C': 116,
       'N': 110,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'O': {'H': -1,
       'C': 113,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'F': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'P': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'S': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'Cl': {'H': -1,
        'C': -1,
        'N': -1,
        'O': -1,
        'F': -1,
        'P': -1,
        'S': -1,
        'Cl': -1,
        'Br': -1,
        'I': -1},
 'Br': {'H': -1,
        'C': -1,
        'N': -1,
        'O': -1,
        'F': -1,
        'P': -1,
        'S': -1,
        'Cl': -1,
        'Br': -1,
        'I': -1},
 'I': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1}}

BONDS_AROMATIC: dict[str, dict[str, int]] = {'H': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'C': {'H': -1,
       'C': 139,
       'N': 134,
       'O': 135,
       'F': -1,
       'P': -1,
       'S': 174,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'N': {'H': -1,
       'C': 134,
       'N': 133,
       'O': 135,
       'F': -1,
       'P': -1,
       'S': 162,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'O': {'H': -1,
       'C': 135,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'F': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'P': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'S': {'H': -1,
       'C': 174,
       'N': 162,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1},
 'Cl': {'H': -1,
        'C': -1,
        'N': -1,
        'O': -1,
        'F': -1,
        'P': -1,
        'S': -1,
        'Cl': -1,
        'Br': -1,
        'I': -1},
 'Br': {'H': -1,
        'C': -1,
        'N': -1,
        'O': -1,
        'F': -1,
        'P': -1,
        'S': -1,
        'Cl': -1,
        'Br': -1,
        'I': -1},
 'I': {'H': -1,
       'C': -1,
       'N': -1,
       'O': -1,
       'F': -1,
       'P': -1,
       'S': -1,
       'Cl': -1,
       'Br': -1,
       'I': -1}}

#: Single / double / triple / aromatic, in the order DiffSMol indexes them.
DIFFSMOL_BOND_TABLES = (
    BONDS_SINGLE,
    BONDS_DOUBLE,
    BONDS_TRIPLE,
    BONDS_AROMATIC,
)
